version: '3.8'

services:
  slidev:
    build:
      context: .
      dockerfile: slidev.dockerfile
    container_name: slidev
    ports:
      - 3030:3030
    command: npm run remote
    volumes:
      - ./:/work
